import Navbar from "@components/navbar/Navbar";
import LoginModal from "@components/navbar/modals/LoginModal";
import ToastProvider from "@components/provider/ToastProvider";

import "./globals.css";
import { Inter } from "next/font/google";

const inter = Inter({ subsets: ["latin"] });

import "./globals.css";
import { Sidebar } from "@components/Sidebar";
import { cn } from "@lib/utils";

export const metadata = {
  title: "Country Profile",
  description: "Generated by IndIAN Oil",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={cn("bg-secondary", inter.className)}>
        <div className="main">
          <div className="gradient"></div>
        </div>

        <main className=" relative z-10 flex flex-col max-w-7xl mx-auto">
          <ToastProvider />
          <Navbar className="hide-on-print" />
          <div className="hidden md:flex mt-16 w-20 flex-col fixed inset-y-0 ">
            <Sidebar className="hide-on-print" />
          </div>

          <LoginModal />

          {children}
        </main>
      </body>
    </html>
  );
}
