import Navbar from '@components/navbar/Navbar'
import LoginModal from '@components/navbar/modals/LoginModal'
import ToastProvider from '@components/provider/ToastProvider'

import './globals.css'
import { Sidebar } from '@components/Sidebar'


export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className=''>
        <div className='main'>
          <div className='gradient'></div>
        </div>
        
        <main className=' relative z-10 flex flex-col max-w-7xl mx-auto'>
          <ToastProvider/>
          <Navbar/>
          <div className='hidden md:flex mt-16 w-20 flex-col fixed inset-y-0 '>
            <Sidebar/>
          </div>
          
          <LoginModal/>
          
          {children}
        </main>
      </body>
    </html>
  )
}
